// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_EG_STORE_0_H
#define WINRT_EG_STORE_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::EG_STORE
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::EG_STORE::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::EG_STORE::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::EG_STORE::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::EG_STORE::MainWindow> = L"EG_STORE.MainWindow";
    template <> inline constexpr auto& name_v<winrt::EG_STORE::XamlMetaDataProvider> = L"EG_STORE.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::EG_STORE::IMainWindow> = L"EG_STORE.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::EG_STORE::IMainWindow>{ 0x68B5FD51,0x2EC7,0x5CA2,{ 0xB5,0x01,0x4A,0xFA,0x7F,0x2E,0x80,0xE6 } }; // 68B5FD51-2EC7-5CA2-B501-4AFA7F2E80E6
    template <> struct default_interface<winrt::EG_STORE::MainWindow>{ using type = winrt::EG_STORE::IMainWindow; };
    template <> struct default_interface<winrt::EG_STORE::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::EG_STORE::IMainWindow>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_EG_STORE_IMainWindow
    {
        [[nodiscard]] WINRT_IMPL_AUTO(int32_t) MyProperty() const;
        WINRT_IMPL_AUTO(void) MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::EG_STORE::IMainWindow>
    {
        template <typename D> using type = consume_EG_STORE_IMainWindow<D>;
    };
}
#endif
