// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

void* winrt_make_EG_STORE_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::EG_STORE::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::EG_STORE
{
    MainWindow::MainWindow() :
        MainWindow(make<EG_STORE::implementation::MainWindow>())
    {
    }
}
